apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: web
  name: app
spec: 
  replicas: 3
  selector: 
    matchLabels: 
      app: web

  template: 
    metadata:
      labels:
        app: web

    spec: 
      containers:
      - name: capstone
        image: ${REPOSITORY_TAG}
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  labels: 
    app: web
  name: app
spec: 
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector: 
    app: web